
const KEY="studentos_dz_v1";
const T={
 ar:{brand:"StudentOS",ultimate:"DZ · ULTIMATE",tag:"Study. Focus. Compete. Improve.",login:"تسجيل الدخول",register:"إنشاء حساب",name:"الاسم الكامل",email:"البريد الإلكتروني",password:"كلمة المرور",confirm:"تأكيد كلمة المرور",enter:"دخول",create:"إنشاء الحساب",have:"لديك حساب؟",no:"ليس لديك حساب؟",dash:"لوحة التحكم",grades:"المعدل",focus:"التركيز",challenges:"التحديات",rooms:"غرف الدراسة",planner:"المخطط",analytics:"التحليلات",settings:"الإعدادات",welcome:"مرحبًا",semester:"معدل الفصل",study:"وقت الدراسة",sessions:"الجلسات",streak:"السلسلة",xp:"XP",level:"المستوى",today:"خطة اليوم",quick:"إجراءات سريعة",start:"ابدأ التركيز",addTask:"أضف مهمة",calc:"احسب المعدل",join:"غرفة دراسة",focusLab:"Focus Lab",mode:"الوضع",subject:"المادة",goal:"هدف الجلسة",startTimer:"ابدأ",pause:"إيقاف مؤقت",resume:"استئناف",reset:"تصفير",skip:"تخطي الراحة",challengesTitle:"تحديات الدراسة",addSubject:"إضافة مادة",add:"إضافة",module:"اسم المادة",coef:"المعامل",cc:"CC/TD",exam:"الامتحان",average:"المعدل",totalCoef:"مجموع المعاملات",passed:"ناجحة",failed:"راسبة",best:"أفضل مادة",worst:"أضعف مادة",addChallenge:"تحدٍ جديد",type:"النوع",target:"الهدف",reward:"المكافأة",plannerTitle:"المخطط الدراسي",taskTitle:"عنوان المهمة",priority:"الأولوية",date:"التاريخ",complete:"إكمال",delete:"حذف",edit:"تعديل",all:"الكل",pending:"قيد الانتظار",completed:"مكتملة",urgent:"عاجلة",roomsTitle:"غرف الدراسة",roomName:"اسم الغرفة",code:"الكود",createRoom:"إنشاء غرفة",joinRoom:"انضمام",leaderboard:"لوحة المتصدرين",analyticsTitle:"التحليلات",todayStudy:"دراسة اليوم",weekStudy:"هذا الأسبوع",monthStudy:"هذا الشهر",avgSession:"متوسط الجلسة",tasksRate:"إنجاز المهام",settingsTitle:"الإعدادات",language:"اللغة",theme:"المظهر",light:"فاتح",dark:"داكن",focusMin:"دقائق التركيز",shortBreak:"الراحة القصيرة",longBreak:"الراحة الطويلة",ccPct:"نسبة CC/TD",examPct:"نسبة الامتحان",export:"تصدير البيانات",import:"استيراد البيانات",resetData:"إعادة ضبط البيانات",logout:"تسجيل الخروج",profile:"الملف الشخصي",save:"حفظ",custom:"مخصص",ready:"جاهز",minutes:"دقيقة",hours:"ساعة",security:"ملاحظة أمنية: هذا نظام حسابات محلي تجريبي. البيانات وكلمات المرور محفوظة محليًا وليست نظام أمان حقيقي.",empty:"لا توجد بيانات بعد.",excellent:"ممتاز",good:"جيد",weak:"دون المتوسط",sessionDone:"تم إكمال جلسة التركيز!",taskDone:"تم إكمال المهمة",saved:"تم الحفظ",resetAsk:"هل أنت متأكد؟ سيتم حذف كل بيانات التطبيق محليًا.",challengeDone:"اكتمل التحدي!",noSubjects:"أضف موادك أولًا",profilePhoto:"صورة الحساب",changePhoto:"تغيير الصورة",daily:"يومي",weekly:"أسبوعي",monthly:"شهري",customType:"مخصص",focusMinutes:"دقائق التركيز",points:"نقطة",week:"الأسبوع",profileEdit:"تعديل الملف الشخصي"},
 fr:{brand:"StudentOS",ultimate:"DZ · ULTIMATE",tag:"Study. Focus. Compete. Improve.",login:"Connexion",register:"Créer un compte",name:"Nom complet",email:"E-mail",password:"Mot de passe",confirm:"Confirmation",enter:"Se connecter",create:"Créer le compte",have:"Vous avez un compte ?",no:"Pas encore de compte ?",dash:"Tableau de bord",grades:"Moyenne",focus:"Focus",challenges:"Défis",rooms:"Salles d'étude",planner:"Planning",analytics:"Analytique",settings:"Paramètres",welcome:"Bienvenue",semester:"Moyenne du semestre",study:"Temps d'étude",sessions:"Sessions",streak:"Série",xp:"XP",level:"Niveau",today:"Plan du jour",quick:"Actions rapides",start:"Démarrer Focus",addTask:"Ajouter une tâche",calc:"Calculer la moyenne",join:"Salle d'étude",focusLab:"Focus Lab",mode:"Mode",subject:"Matière",goal:"Objectif",startTimer:"Démarrer",pause:"Pause",resume:"Reprendre",reset:"Réinitialiser",skip:"Passer la pause",challengesTitle:"Défis d'étude",addSubject:"Ajouter une matière",add:"Ajouter",module:"Matière",coef:"Coefficient",cc:"CC/TD",exam:"Examen",average:"Moyenne",totalCoef:"Total coefficients",passed:"Validées",failed:"Non validées",best:"Meilleure",worst:"Plus faible",addChallenge:"Nouveau défi",type:"Type",target:"Objectif",reward:"Récompense",plannerTitle:"Planning d'étude",taskTitle:"Titre",priority:"Priorité",date:"Date",complete:"Terminer",delete:"Supprimer",edit:"Modifier",all:"Toutes",pending:"En attente",completed:"Terminées",urgent:"Urgentes",roomsTitle:"Salles d'étude",roomName:"Nom",code:"Code",createRoom:"Créer une salle",joinRoom:"Rejoindre",leaderboard:"Classement",analyticsTitle:"Analytique",todayStudy:"Aujourd'hui",weekStudy:"Cette semaine",monthStudy:"Ce mois",avgSession:"Durée moyenne",tasksRate:"Tâches terminées",settingsTitle:"Paramètres",language:"Langue",theme:"Thème",light:"Clair",dark:"Sombre",focusMin:"Minutes focus",shortBreak:"Pause courte",longBreak:"Pause longue",ccPct:"CC/TD %",examPct:"Examen %",export:"Exporter les données",import:"Importer les données",resetData:"Réinitialiser",logout:"Déconnexion",profile:"Profil",save:"Enregistrer",custom:"Personnalisé",ready:"Prêt",minutes:"min",hours:"h",security:"Note sécurité : compte local de démonstration. Les données et mots de passe sont stockés localement et ne constituent pas une vraie sécurité.",empty:"Aucune donnée.",excellent:"Excellent",good:"Bien",weak:"Sous la moyenne",sessionDone:"Session terminée !",taskDone:"Tâche terminée",saved:"Enregistré",resetAsk:"Êtes-vous sûr ? Toutes les données locales seront supprimées.",challengeDone:"Défi terminé !",noSubjects:"Ajoutez d'abord des matières",profilePhoto:"Photo de profil",changePhoto:"Changer la photo",daily:"Quotidien",weekly:"Hebdomadaire",monthly:"Mensuel",customType:"Personnalisé",focusMinutes:"Minutes focus",points:"points",week:"Semaine",profileEdit:"Modifier le profil"},
 en:{brand:"StudentOS",ultimate:"DZ · ULTIMATE",tag:"Study. Focus. Compete. Improve.",login:"Login",register:"Create account",name:"Full name",email:"Email",password:"Password",confirm:"Confirm password",enter:"Login",create:"Create account",have:"Already have an account?",no:"Don't have an account?",dash:"Dashboard",grades:"Grades",focus:"Focus",challenges:"Challenges",rooms:"Study Rooms",planner:"Planner",analytics:"Analytics",settings:"Settings",welcome:"Welcome",semester:"Semester average",study:"Study time",sessions:"Sessions",streak:"Streak",xp:"XP",level:"Level",today:"Today's plan",quick:"Quick actions",start:"Start Focus",addTask:"Add task",calc:"Calculate average",join:"Study room",focusLab:"Focus Lab",mode:"Mode",subject:"Subject",goal:"Session goal",startTimer:"Start",pause:"Pause",resume:"Resume",reset:"Reset",skip:"Skip break",challengesTitle:"Study Challenges",addSubject:"Add subject",add:"Add",module:"Subject",coef:"Coefficient",cc:"CC/TD",exam:"Exam",average:"Average",totalCoef:"Total coefficients",passed:"Passed",failed:"Failed",best:"Best subject",worst:"Weakest subject",addChallenge:"New challenge",type:"Type",target:"Target",reward:"Reward",plannerTitle:"Study Planner",taskTitle:"Task title",priority:"Priority",date:"Date",complete:"Complete",delete:"Delete",edit:"Edit",all:"All",pending:"Pending",completed:"Completed",urgent:"Urgent",roomsTitle:"Study Rooms",roomName:"Room name",code:"Code",createRoom:"Create room",joinRoom:"Join",leaderboard:"Leaderboard",analyticsTitle:"Analytics",todayStudy:"Today",weekStudy:"This week",monthStudy:"This month",avgSession:"Average session",tasksRate:"Task completion",settingsTitle:"Settings",language:"Language",theme:"Theme",light:"Light",dark:"Dark",focusMin:"Focus minutes",shortBreak:"Short break",longBreak:"Long break",ccPct:"CC/TD %",examPct:"Exam %",export:"Export data",import:"Import data",resetData:"Reset data",logout:"Log out",profile:"Profile",save:"Save",custom:"Custom",ready:"Ready",minutes:"min",hours:"h",security:"Security note: this is a local demo account system. Data and passwords are stored locally and are not real security.",empty:"No data yet.",excellent:"Excellent",good:"Good",weak:"Below average",sessionDone:"Focus session completed!",taskDone:"Task completed",saved:"Saved",resetAsk:"Are you sure? All local app data will be deleted.",challengeDone:"Challenge completed!",noSubjects:"Add subjects first",profilePhoto:"Profile photo",changePhoto:"Change photo",daily:"Daily",weekly:"Weekly",monthly:"Monthly",customType:"Custom",focusMinutes:"Focus minutes",points:"points",week:"Week",profileEdit:"Edit profile"}
};
const icons={dash:"⌂",grades:"◫",focus:"◉",challenges:"◇",rooms:"◎",planner:"✓",analytics:"▥",settings:"⚙"};
const $=s=>document.querySelector(s);
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-4);
const today=()=>new Date().toISOString().slice(0,10);
const defaultState=()=>({auth:null,profile:null,subjects:[],tasks:[],sessions:[],challenges:[],rooms:[],settings:{lang:"ar",theme:"light",focus:25,short:5,long:15,cc:40,exam:60},analytics:{},timer:{mode:"focus",remaining:1500,running:false,startedAt:null,subject:"",goal:""}});

const Store={
 get(){try{return JSON.parse(localStorage.getItem(KEY))||defaultState()}catch{return defaultState()}},
 set(s){localStorage.setItem(KEY,JSON.stringify(s));return s},
 patch(fn){const s=this.get();fn(s);this.set(s);return s},
 reset(){localStorage.removeItem(KEY)}
};
let state=Store.get(), page="dash", authMode="login", timerInt=null;

function t(k){return T[state.settings.lang]?.[k]||T.en[k]||k}
function toast(msg){const x=document.createElement("div");x.className="toast";x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function save(){Store.set(state)}
function xpLevel(x){return Math.floor((x||0)/500)+1}
function xpInto(x){return (x||0)%500}
function addXP(n){state.profile.xp=(state.profile.xp||0)+n; checkChallenges(); save()}
function studyMinutes(){return Math.round(state.sessions.reduce((a,s)=>a+(s.minutes||0),0))}
function semesterAvg(){let total=0,coef=0;state.subjects.forEach(s=>{if(Number(s.coef)>0){let cc=Number(s.cc),ex=Number(s.exam);let avg=null;if(Number.isFinite(cc)&&Number.isFinite(ex))avg=cc*state.settings.cc/100+ex*state.settings.exam/100;else if(Number.isFinite(cc))avg=cc;else if(Number.isFinite(ex))avg=ex;if(avg!==null){total+=avg*Number(s.coef);coef+=Number(s.coef)}}});return coef?total/coef:null}
function streak(){let days=[...new Set(state.sessions.map(s=>s.date))].sort().reverse();if(!days.length)return 0;let n=0,d=new Date();for(const x of days){let target=new Date(d);target.setDate(target.getDate()-n);if(x===target.toISOString().slice(0,10))n++;else break}return n}
function checkChallenges(){
  const mins=studyMinutes(), done=state.tasks.filter(x=>x.done).length, sess=state.sessions.length;
  state.challenges.forEach(c=>{if(c.kind==="minutes")c.current=mins;if(c.kind==="sessions")c.current=sess;if(c.kind==="tasks")c.current=done;if(c.kind==="xp")c.current=state.profile.xp||0;if(c.kind==="streak")c.current=streak();if(c.current>=c.target&&!c.completed){c.completed=true;state.profile.xp+=Number(c.reward)||0;toast(t("challengeDone"))}});
}
function navButton(k){return `<button class="${page===k?"active":""}" onclick="go('${k}')">${icons[k]||"•"} ${t(k)}</button>`}
function layout(content){
  document.documentElement.lang=state.settings.lang;document.documentElement.dir=state.settings.lang==="ar"?"rtl":"ltr";
  document.body.classList.toggle("dark",state.settings.theme==="dark");
  const nav=["dash","grades","focus","challenges","rooms","planner","analytics","settings"];
  $("#app").innerHTML=`<div class="shell"><aside class="side"><div class="brand"><div class="logo">${t("brand")} <span>DZ</span></div><div class="muted">${t("ultimate")}</div></div><nav class="nav">${nav.map(navButton).join("")}</nav><div class="side-bottom"><button class="nav" style="width:100%" onclick="logout()">${icons.settings} ${t("logout")}</button></div></aside><main class="main"><div class="top"><div><h1>${title()}</h1><div class="muted">${t("tag")}</div></div><div class="actions"><button class="btn secondary" onclick="go('settings')">⚙</button>${profileAvatar()}</div></div>${content}</main><nav class="mobile-nav">${["dash","focus","planner","challenges","settings"].map(navButton).join("")}</nav></div>`;
}
function title(){return ({dash:t("dash"),grades:t("grades"),focus:t("focusLab"),challenges:t("challengesTitle"),rooms:t("roomsTitle"),planner:t("plannerTitle"),analytics:t("analyticsTitle"),settings:t("settingsTitle")})[page]}
function profileAvatar(){let p=state.profile||{};return p.photo?`<img class="avatar" src="${p.photo}" alt="">`:`<div class="avatar">${esc((p.name||"U")[0])}</div>`}
function go(p){page=p;render()}

function render(){state=Store.get();if(!state.auth){renderAuth();return}checkChallenges();save();({dash:renderDash,grades:renderGrades,focus:renderFocus,challenges:renderChallenges,rooms:renderRooms,planner:renderPlanner,analytics:renderAnalytics,settings:renderSettings}[page]||renderDash)()}
function renderAuth(){
 document.documentElement.lang=state.settings.lang;document.documentElement.dir=state.settings.lang==="ar"?"rtl":"ltr";
 $("#app").innerHTML=`<div class="auth"><div class="auth-card"><div class="logo">${t("brand")} <span>DZ</span></div><div class="tag">${t("ultimate")} · ${t("tag")}</div><div class="bar"><button class="btn secondary" onclick="setLang('ar')">AR</button><button class="btn secondary" onclick="setLang('fr')">FR</button><button class="btn secondary" onclick="setLang('en')">EN</button></div><h2>${authMode==="login"?t("login"):t("register")}</h2><form onsubmit="authSubmit(event)">${authMode==="register"?`<div class="field"><label>${t("name")}</label><input id="aName" required></div>`:""}<div class="field"><label>${t("email")}</label><input id="aEmail" type="email" required></div><div class="field"><label>${t("password")}</label><input id="aPass" type="password" required></div>${authMode==="register"?`<div class="field"><label>${t("confirm")}</label><input id="aConfirm" type="password" required></div><div class="field"><label>${t("profilePhoto")}</label><input id="aPhoto" type="file" accept="image/*"></div>`:""}<button class="btn" style="width:100%;margin-top:8px">${authMode==="login"?t("enter"):t("create")}</button></form><div class="auth-switch">${authMode==="login"?t("no"):t("have")} <span class="link" onclick="authMode='${authMode==="login"?"register":"login"}';renderAuth()">${authMode==="login"?t("register"):t("login")}</span></div><p class="muted" style="font-size:12px;margin-top:18px">${t("security")}</p></div></div>`;
}
function setLang(l){state.settings.lang=l;save();render()}
async function authSubmit(e){
 e.preventDefault();const email=$("#aEmail").value.trim().toLowerCase(),pass=$("#aPass").value;
 if(authMode==="register"){if(pass!==$("#aConfirm").value)return toast(t("confirm"));let photo="";const f=$("#aPhoto").files[0];if(f)photo=await readFile(f);state.auth={email,password:pass};state.profile={name:$("#aName").value.trim(),email,photo,xp:0};state.challenges=starterChallenges();save();toast(t("saved"))}
 else {if(!state.auth||state.auth.email!==email||state.auth.password!==pass)return toast("Login failed");state.profile=state.profile||{name:email.split("@")[0],email,xp:0}}
 state.auth.email=email;state.auth.password=pass;save();render()
}
function logout(){state.auth=null;save();authMode="login";render()}
function readFile(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function starterChallenges(){return[{id:uid(),title:"60 minutes",kind:"minutes",target:60,current:0,reward:100,completed:false},{id:uid(),title:"3 focus sessions",kind:"sessions",target:3,current:0,reward:150,completed:false},{id:uid(),title:"5 completed tasks",kind:"tasks",target:5,current:0,reward:200,completed:false},{id:uid(),title:"500 XP",kind:"xp",target:500,current:0,reward:250,completed:false}]}

function renderDash(){
 const avg=semesterAvg(), xp=state.profile.xp||0, lvl=xpLevel(xp), into=xpInto(xp), tasks=state.tasks.filter(x=>x.date===today()&&!x.done);
 layout(`<div class="grid stats"><div class="card stat"><div class="label">${t("semester")}</div><div class="value">${avg===null?"—":avg.toFixed(2)}<small>/20</small></div></div><div class="card stat"><div class="label">${t("study")}</div><div class="value">${studyMinutes()}<small> ${t("minutes")}</small></div></div><div class="card stat"><div class="label">${t("sessions")}</div><div class="value">${state.sessions.length}</div></div><div class="card stat"><div class="label">${t("streak")}</div><div class="value">${streak()} 🔥</div></div><div class="card stat"><div class="label">${t("xp")}</div><div class="value">${xp}</div></div><div class="card stat"><div class="label">${t("level")}</div><div class="value">${lvl}</div></div></div>
 <div class="grid two"><section class="card"><div class="section-title"><h2>${t("today")}</h2><button class="btn secondary" onclick="go('planner')">+ ${t("addTask")}</button></div>${tasks.length?tasks.map(taskRow).join(""):`<div class="empty">${t("empty")}</div>`}</section>
 <section class="card"><div class="section-title"><h2>${t("level")} ${lvl}</h2><strong>${into}/500 XP</strong></div><div class="progress"><i style="width:${into/5}%"></i></div><p class="muted">${500-into} XP</p><div class="bar"><button class="btn" onclick="go('focus')">◉ ${t("start")}</button><button class="btn secondary" onclick="go('grades')">◫ ${t("calc")}</button><button class="btn secondary" onclick="go('rooms')">◎ ${t("join")}</button></div></section></div>
 <div class="section-title"><h2>${t("challengesTitle")}</h2><button class="link" onclick="go('challenges')">${t("all")}</button></div><div class="grid three">${state.challenges.slice(0,3).map(challengeCard).join("")||`<div class="card empty">${t("empty")}</div>`}</div>`)
}
function taskRow(x){return `<div class="task"><div><strong class="${x.done?"muted":""}">${esc(x.title)}</strong><div class="muted">${esc(x.subject||"")} · ${x.date||""}</div></div><button class="btn secondary" onclick="toggleTask('${x.id}')">${x.done?"✓":t("complete")}</button></div>`}
function challengeCard(c){let p=Math.min(100,c.target?c.current/c.target*100:0);return `<div class="card challenge"><div><span class="pill">${c.completed?"✓":t(c.kind==="minutes"?"minutes":"xp")}</span><h3>${esc(c.title)}</h3><div class="progress"><i style="width:${p}%"></i></div><small class="muted">${Math.min(c.current,c.target)}/${c.target} · +${c.reward} XP</small></div></div>`}

function renderGrades(){
 const avg=semesterAvg(), valid=state.subjects.filter(s=>Number(s.coef)>0&&Number.isFinite(Number(s.cc))&&Number.isFinite(Number(s.exam))).map(s=>({...s,avg:Number(s.cc)*state.settings.cc/100+Number(s.exam)*state.settings.exam/100}));
 const pass=valid.filter(s=>s.avg>=10), fail=valid.filter(s=>s.avg<10), best=valid.sort((a,b)=>b.avg-a.avg)[0], worst=valid[valid.length-1];
 layout(`<section class="card"><div class="section-title"><h2>${t("grades")}</h2><button class="btn" onclick="addSubject()">${t("addSubject")}</button></div><div class="table-wrap"><table class="table"><thead><tr><th>${t("module")}</th><th>${t("coef")}</th><th>${t("cc")}</th><th>${t("exam")}</th><th>${t("average")}</th><th></th></tr></thead><tbody>${state.subjects.map((s,i)=>`<tr><td><input value="${esc(s.name)}" onchange="editSubject(${i},'name',this.value)"></td><td><input type="number" min="0" value="${s.coef}" onchange="editSubject(${i},'coef',this.value)"></td><td><input type="number" min="0" max="20" value="${s.cc??""}" onchange="editSubject(${i},'cc',this.value)"></td><td><input type="number" min="0" max="20" value="${s.exam??""}" onchange="editSubject(${i},'exam',this.value)"></td><td><strong>${moduleAvg(s)}</strong></td><td><button class="btn danger" onclick="deleteSubject(${i})">×</button></td></tr>`).join("")}</tbody></table></div></section>
 <div class="grid three" style="margin-top:16px"><div class="card stat"><div class="label">${t("semester")}</div><div class="value">${avg===null?"—":avg.toFixed(2)}/20</div></div><div class="card"><b>${t("passed")}</b><div class="value success">${pass.length}</div></div><div class="card"><b>${t("failed")}</b><div class="value danger-text">${fail.length}</div></div></div>
 <div class="grid two" style="margin-top:16px"><div class="card"><b>${t("best")}</b><p>${best?esc(best.name)+" · "+best.avg.toFixed(2):"—"}</p></div><div class="card"><b>${t("worst")}</b><p>${worst?esc(worst.name)+" · "+worst.avg.toFixed(2):"—"}</p></div></div>`)
}
function moduleAvg(s){let cc=Number(s.cc),ex=Number(s.exam);if(!Number.isFinite(cc)||!Number.isFinite(ex))return "—";return (cc*state.settings.cc/100+ex*state.settings.exam/100).toFixed(2)}
function addSubject(){state.subjects.push({id:uid(),name:"New module",coef:1,cc:10,exam:10});save();render()}
function editSubject(i,k,v){state.subjects[i][k]=k==="name"?v:Number(v);save();render()}
function deleteSubject(i){if(confirm(t("resetAsk").replace("All local app data will be deleted.",""))){state.subjects.splice(i,1);save();render()}}

function renderFocus(){
 const tm=state.timer, total=tm.mode==="focus"?Number(tm.focusTotal||state.settings.focus*60):Number(tm.breakTotal||state.settings.short*60), pct=Math.max(0,Math.min(100,(1-tm.remaining/Math.max(total,1))*100));
 layout(`<div class="grid two"><section class="card timer"><div class="circle" style="--pct:${pct}%"><div class="timer-content"><div class="muted">${tm.mode==="focus"?t("focus"):t("shortBreak")}</div><div class="time">${fmt(tm.remaining)}</div><div class="muted">${tm.running?"●":"○"} ${tm.running?t("startTimer"):t("ready")}</div></div></div><div class="timer-controls"><button class="btn" onclick="timerStart()">${tm.running?t("pause"):t("startTimer")}</button><button class="btn secondary" onclick="timerReset()">${t("reset")}</button><button class="btn secondary" onclick="timerSkip()">${t("skip")}</button></div></section>
 <section class="card"><h2>${t("mode")}</h2><div class="bar">${[[25,5],[50,10],[90,15]].map(x=>`<button class="btn secondary" onclick="setTimer(${x[0]},${x[1]})">${x[0]}/${x[1]}</button>`).join("")}<button class="btn secondary" onclick="customTimer()">${t("custom")}</button></div><div class="field"><label>${t("subject")}</label><select id="focusSubject"><option value="">—</option>${state.subjects.map(s=>`<option ${tm.subject===s.name?"selected":""}>${esc(s.name)}</option>`).join("")}</select></div><div class="field"><label>${t("goal")}</label><input id="focusGoal" value="${esc(tm.goal||"")}"></div><div class="section-title"><h2>${t("sessions")}</h2></div>${state.sessions.slice().reverse().slice(0,8).map(s=>`<div class="session"><span>${esc(s.subject||"Focus")}</span><span>${s.minutes} ${t("minutes")}</span></div>`).join("")||`<div class="empty">${t("empty")}</div>`}</section></div>`)
}
function fmt(sec){sec=Math.max(0,Math.round(sec));return String(Math.floor(sec/60)).padStart(2,"0")+":"+String(sec%60).padStart(2,"0")}
function syncFocusFields(){state.timer.subject=$("#focusSubject")?.value||state.timer.subject;state.timer.goal=$("#focusGoal")?.value||state.timer.goal;save()}
function setTimer(f,b){syncFocusFields();state.timer={...state.timer,mode:"focus",remaining:f*60,focusTotal:f*60,breakTotal:b*60,running:false};save();render()}
function customTimer(){let f=Number(prompt(t("focusMinutes"),state.settings.focus)),b=Number(prompt(t("shortBreak"),state.settings.short));if(f>0&&b>=0)setTimer(f,b)}
function timerStart(){syncFocusFields();if(state.timer.running){state.timer.running=false;clearInterval(timerInt);save();render();return}state.timer.running=true;save();clearInterval(timerInt);timerInt=setInterval(()=>{state=Store.get();if(!state.timer.running){clearInterval(timerInt);return}state.timer.remaining--;if(state.timer.remaining<=0){state.timer.running=false;if(state.timer.mode==="focus"){let mins=Math.round((state.timer.focusTotal||state.settings.focus*60)/60);state.sessions.push({id:uid(),date:today(),minutes:mins,subject:state.timer.subject||"Focus",goal:state.timer.goal||""});state.profile.xp+=mins;toast(t("sessionDone"));state.profile.streak=streak();state.timer.mode="break";state.timer.remaining=state.timer.breakTotal||state.settings.short*60}else{state.timer.mode="focus";state.timer.remaining=state.timer.focusTotal||state.settings.focus*60}checkChallenges()}save();render()},1000);render()}
function timerReset(){clearInterval(timerInt);state.timer.running=false;state.timer.mode="focus";state.timer.remaining=state.timer.focusTotal||state.settings.focus*60;save();render()}
function timerSkip(){clearInterval(timerInt);state.timer.running=false;state.timer.mode=state.timer.mode==="focus"?"break":"focus";state.timer.remaining=state.timer.mode==="focus"?(state.timer.focusTotal||state.settings.focus*60):(state.timer.breakTotal||state.settings.short*60);save();render()}

function renderChallenges(){
 layout(`<div class="section-title"><h2>${t("challengesTitle")}</h2><button class="btn" onclick="addChallenge()">${t("addChallenge")}</button></div><div class="grid two">${state.challenges.map(challengeCard).join("")||`<div class="card empty">${t("empty")}</div>`}</div><div class="section-title"><h2>🏆 Badges</h2></div><div class="grid three"><div class="card"><b>First Session</b><p class="muted">${state.sessions.length?"✓":"—"}</p></div><div class="card"><b>7 Day Streak</b><p class="muted">${streak()>=7?"✓":"—"}</p></div><div class="card"><b>1000 XP</b><p class="muted">${(state.profile.xp||0)>=1000?"✓":"—"}</p></div></div>`)
}
function addChallenge(){let title=prompt(t("addChallenge"));if(!title)return;let target=Number(prompt(t("target"),60));let reward=Number(prompt(t("reward"),100));state.challenges.push({id:uid(),title,kind:"minutes",target,current:0,reward,completed:false});save();render()}

function renderPlanner(){
 const filter=window.taskFilter||"all";let list=state.tasks.filter(x=>filter==="all"||filter==="today"&&x.date===today()||filter==="pending"&&!x.done||filter==="completed"&&x.done||filter==="urgent"&&x.priority==="Urgent");
 layout(`<section class="card"><div class="section-title"><h2>${t("plannerTitle")}</h2><button class="btn" onclick="addTask()">${t("addTask")}</button></div><div class="bar">${["all","today","pending","completed","urgent"].map(f=>`<button class="btn ${filter===f?"":"secondary"}" onclick="taskFilter='${f}';render()">${t(f)}</button>`).join("")}</div>${list.length?list.map(taskRow).join(""):`<div class="empty">${t("empty")}</div>`}</section>`)
}
function addTask(){let title=prompt(t("taskTitle"));if(!title)return;let date=prompt(t("date"),today())||today();let priority=prompt(t("priority"),"Normal")||"Normal";let subject=prompt(t("subject"),"")||"";state.tasks.push({id:uid(),title,date,priority,subject,done:false});save();render()}
function toggleTask(id){let x=state.tasks.find(a=>a.id===id);if(!x)return;x.done=!x.done;if(x.done){state.profile.xp+=50;toast(t("taskDone"))}checkChallenges();save();render()}

function renderRooms(){
 layout(`<section class="card"><div class="section-title"><h2>${t("roomsTitle")}</h2><div class="bar"><button class="btn" onclick="createRoom()">${t("createRoom")}</button><button class="btn secondary" onclick="joinRoom()">${t("joinRoom")}</button></div></div>${state.rooms.length?state.rooms.map(r=>`<div class="room-row"><div><strong>${esc(r.name)}</strong><div class="muted">${t("code")}: ${r.code}</div></div><span class="pill">${r.members?.length||1}</span></div>`).join(""):`<div class="empty">${t("empty")}</div>`}<p class="muted">${t("security").split(".")[0]} · Study Rooms are local.</p></section><section class="card" style="margin-top:16px"><h2>${t("leaderboard")}</h2><div class="room-row"><strong>1 · ${esc(state.profile.name)}</strong><span>${studyMinutes()} min · ${state.profile.xp||0} XP</span></div></section>`)
}
function createRoom(){let name=prompt(t("roomName"));if(!name)return;state.rooms.push({id:uid(),name,code:"DZ-"+Math.floor(1000+Math.random()*9000),members:[{name:state.profile.name,xp:state.profile.xp||0} ]});save();render()}
function joinRoom(){let code=prompt(t("code"));let r=state.rooms.find(x=>x.code===code);toast(r?"Joined":"Room not found")}

function renderAnalytics(){
 let now=new Date(), days=[];for(let i=6;i>=0;i--){let d=new Date(now);d.setDate(now.getDate()-i);let ds=d.toISOString().slice(0,10);days.push({d:ds,m:state.sessions.filter(s=>s.date===ds).reduce((a,s)=>a+s.minutes,0)})}
 let total=studyMinutes(), week=days.reduce((a,x)=>a+x.m,0), month=state.sessions.filter(s=>s.date?.slice(0,7)===today().slice(0,7)).reduce((a,s)=>a+s.minutes,0), avg=state.sessions.length?total/state.sessions.length:0, done=state.tasks.length?state.tasks.filter(x=>x.done).length/state.tasks.length*100:0;
 let max=Math.max(1,...days.map(x=>x.m));
 layout(`<div class="grid three"><div class="card stat"><div class="label">${t("study")}</div><div class="value">${total}m</div></div><div class="card stat"><div class="label">${t("weekStudy")}</div><div class="value">${week}m</div></div><div class="card stat"><div class="label">${t("monthStudy")}</div><div class="value">${month}m</div></div><div class="card stat"><div class="label">${t("avgSession")}</div><div class="value">${avg.toFixed(1)}m</div></div><div class="card stat"><div class="label">${t("tasksRate")}</div><div class="value">${done.toFixed(0)}%</div></div><div class="card stat"><div class="label">${t("xp")}</div><div class="value">${state.profile.xp||0}</div></div></div>
 <section class="card" style="margin-top:16px"><h2>${t("weekStudy")}</h2>${days.map(x=>`<div style="display:grid;grid-template-columns:70px 1fr 45px;gap:10px;align-items:center;margin:12px 0"><span class="muted">${x.d.slice(5)}</span><div class="progress"><i style="width:${x.m/max*100}%"></i></div><b>${x.m}m</b></div>`).join("")}</section>`)
}

function renderSettings(){
 layout(`<div class="grid two"><section class="card"><h2>${t("profileEdit")}</h2><div style="display:flex;gap:15px;align-items:center;margin:15px 0">${profileAvatar()}<div><b>${esc(state.profile.name)}</b><div class="muted">${esc(state.profile.email)}</div></div></div><div class="field"><label>${t("name")}</label><input id="pName" value="${esc(state.profile.name)}"></div><div class="field"><label>${t("profilePhoto")}</label><input id="pPhoto" type="file" accept="image/*"></div><button class="btn" onclick="saveProfile()">${t("save")}</button></section>
 <section class="card"><h2>${t("settingsTitle")}</h2><div class="field"><label>${t("language")}</label><select onchange="state.settings.lang=this.value;save();render()"><option value="ar" ${state.settings.lang==="ar"?"selected":""}>العربية</option><option value="fr" ${state.settings.lang==="fr"?"selected":""}>Français</option><option value="en" ${state.settings.lang==="en"?"selected":""}>English</option></select></div><div class="field"><label>${t("theme")}</label><select onchange="state.settings.theme=this.value;save();render()"><option value="light" ${state.settings.theme==="light"?"selected":""}>${t("light")}</option><option value="dark" ${state.settings.theme==="dark"?"selected":""}>${t("dark")}</option></select></div><div class="grid two"><div class="field"><label>${t("focusMin")}</label><input type="number" id="setFocus" value="${state.settings.focus}"></div><div class="field"><label>${t("shortBreak")}</label><input type="number" id="setShort" value="${state.settings.short}"></div><div class="field"><label>${t("longBreak")}</label><input type="number" id="setLong" value="${state.settings.long}"></div><div class="field"><label>${t("ccPct")}</label><input type="number" id="setCC" value="${state.settings.cc}"></div><div class="field"><label>${t("examPct")}</label><input type="number" id="setExam" value="${state.settings.exam}"></div></div><button class="btn" onclick="saveSettings()">${t("save")}</button></section></div>
 <div class="grid two" style="margin-top:16px"><section class="card"><h2>${t("export")}</h2><button class="btn" onclick="exportData()">${t("export")}</button><label class="btn secondary" style="display:inline-block;margin:8px;cursor:pointer">${t("import")}<input type="file" accept="application/json" hidden onchange="importData(this.files[0])"></label></section><section class="card danger-zone"><h2>${t("resetData")}</h2><button class="btn danger" onclick="resetAll()">${t("resetData")}</button></section></div>`)
}
async function saveProfile(){state.profile.name=$("#pName").value.trim()||state.profile.name;let f=$("#pPhoto").files[0];if(f)state.profile.photo=await readFile(f);save();toast(t("saved"));render()}
function saveSettings(){state.settings.focus=Number($("#setFocus").value)||25;state.settings.short=Number($("#setShort").value)||5;state.settings.long=Number($("#setLong").value)||15;state.settings.cc=Number($("#setCC").value)||40;state.settings.exam=Number($("#setExam").value)||60;state.timer={...state.timer,remaining:state.settings.focus*60,focusTotal:state.settings.focus*60,breakTotal:state.settings.short*60};save();toast(t("saved"));render()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="studentos-dz-backup.json";a.click();URL.revokeObjectURL(a.href)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.settings||!x.profile)return toast("Invalid backup");state=x;save();render();toast(t("saved"))}catch{toast("Invalid backup")}};r.readAsText(file)}
function resetAll(){if(confirm(t("resetAsk"))){Store.reset();state=defaultState();render()}}
render();
